services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: 'db'
      MYSQL_PORT: 3306
      MYSQL_DB: 'businesses'
      MYSQL_USER: 'businesses'
      MYSQL_PASSWORD: 'hunter2'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    expose:
      - '8000'
  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'businesses'
      MYSQL_USER: 'businesses'
      MYSQL_PASSWORD: 'hunter2'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 100